# Details on the system module

**For a description on how to use the most important functionality, please checkout the tutorials and the API documentation.**

The following example code shows how to use most of the functionality of the `tempo.system` module. This code is *suplementary* to the documentation and also includes functionality that is only relevant to the inner workings of the TimeEvolvingMPO package. Sections that show example code that is not part of the API is marked with three asterix `***`.

**Contents:**

* A: System class
    * A1: liouvillian() ***
* B: TimeDependentSystem class
    * B1: liouvillian(t) ***

In [1]:
import sys
sys.path.insert(0,'..')

import numpy as np

import time_evolving_mpo as tempo

## A: System class

In [2]:
sys_A = tempo.System(tempo.operators.sigma("z"),
                     gammas=[0.2,0.1,0.05],
                     lindblad_operators=[tempo.operators.sigma("x"),
                                         tempo.operators.sigma("y"),
                                         tempo.operators.sigma("z")],
                     name="QDot 3",
                     description="This is a description bla bla.",
                     description_dict={"qdot_nr":3}
                    )

In [3]:
print(sys_A)

----------------------------------------------
System object: QDot 3
 This is a description bla bla.



In [4]:
sys_A.hamiltonian

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [5]:
sys_A.gammas

[0.2, 0.1, 0.05]

In [6]:
sys_A.lindblad_operators

[array([[0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j]]),
 array([[ 0.+0.j, -0.-1.j],
        [ 0.+1.j,  0.+0.j]]),
 array([[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]])]

### A1: liouvillian() ***

In [7]:
sys_A.liouvillian()

array([[-0.3+0.j,  0. +0.j,  0. +0.j,  0.3+0.j],
       [ 0. +0.j, -0.4-2.j,  0.1+0.j,  0. +0.j],
       [ 0. +0.j,  0.1+0.j, -0.4+2.j,  0. +0.j],
       [ 0.3+0.j,  0. +0.j,  0. +0.j, -0.3+0.j]])

## B: TimeDependentSystem class

In [8]:
sys_B = tempo.TimeDependentSystem(
            lambda t: t*tempo.operators.sigma("z"),
            gammas=[lambda t: t*0.3, lambda t: t*0.2, lambda t: t*0.1],
            lindblad_operators=[lambda t: t*tempo.operators.sigma("x"),
                                lambda t: t*tempo.operators.sigma("y"),
                                lambda t: t*tempo.operators.sigma("z")],
            name="QDot 3",
            description="This is a description bla bla.",
            description_dict={"qdot_nr":3})

In [9]:
print(sys_B)

----------------------------------------------
TimeDependentSystem object: QDot 3
 This is a description bla bla.



In [10]:
sys_B.hamiltonian(3.0)

array([[ 3.+0.j,  0.+0.j],
       [ 0.+0.j, -3.+0.j]])

In [11]:
sys_B.gammas[1](1.0)

array(0.2)

In [12]:
sys_B.lindblad_operators[1](1.0)

array([[0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j]])

### B1: liouvillian(t) ***

In [13]:
sys_B.liouvillian(2.0)

array([[-4. +0.j,  0. +0.j,  0. +0.j,  4. +0.j],
       [ 0. +0.j, -5.6-4.j,  0.8+0.j,  0. +0.j],
       [ 0. +0.j,  0.8+0.j, -5.6+4.j,  0. +0.j],
       [ 4. +0.j,  0. +0.j,  0. +0.j, -4. +0.j]])